#
#       _
#   ___/_)
#  (, /      ,_   _
#    /   (_(_/ (_(_(_
#  CX________________
#                    )
#
#  Luna
#  A web application and API framework in modern C++
#
#  Copyright © 2016–2018 D.E. Goodman-Wilson
#

# Site settings
product_name: &product_name Luna
title: *product_name
version: 5.0.0
email: degoodmanwilson@gmail.com
description: >
  A web application and API framework in modern C++
# Build settings
markdown: kramdown
gems:
  - jemoji
